spring:
  zipkin:
    baseUrl: ${ZIPKIN_SERVER:http://localhost:9411}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
security:
  oauth2:
    client:
      client-id: appclient@123
    resource:
      id: microservice1
      jwt:
        key-value: JWTKey@123
